command /ping [<player>]:
    permission: skript.ping.use
    trigger:
        if arg-1 is set:
            if player has permission "skript.ping.others":
                send "&e&l[PING] &aPing &e%arg-1%&a: %ping of arg-1%ms"
            else:
                send "&e&l[PING] &cNie masz uprawnień do sprawdzania pingów innych!"
        else:
            send "&e&l[PING] &aTwój ping: &e%ping of player%ms"